# This is a basic workflow to help you get started with Actions

name: PR - Build / Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: false
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Run JUnit tests
        run: mvn --batch-mode --update-snapshots test
      - name: Generate Surefire HTML report
        run: mvn surefire-report:report
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: surefire-report
          path: target/site/surefire-report.html
      - name: Publish JUnit results
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Tests
          path: target/surefire-reports/*.xml
          reporter: junit

